=== rekateglas/WWSAMBxmlGyak/XMLFeladatWwsamb/XMLSchemaWwsamb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xs:element name="root">
<xs:complexType>
<xs:sequence>
<xs:element name="besztel" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BeszTelSzam">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idBeszállító">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
<xs:element name="beszállítók" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idBeszállító">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="beszállító_neve">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="beszállítók_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="idBeszállító"/>
		</xs:key>
		<xs:keyref name="besztel_ForeignKey_1" refer="beszállítók_PrimaryKey_1">
			<xs:selector xpath="besztel"/>
			<xs:field xpath="idBeszállító"/>
		</xs:keyref>
		<xs:keyref name="nm_kapcsolat_ForeignKey_2" refer="beszállítók_PrimaryKey_1">
			<xs:selector xpath="nm_kapcsolat"/>
			<xs:field xpath="idBeszállító"/>
		</xs:keyref>
	</xs:element>
<xs:element name="boltok" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="helye">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idBolt">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dolgozók_száma">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="árucsere_dátuma" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:date">
							<xs:minInclusive value="1000-01-01"/>
							<xs:maxInclusive value="9999-12-31"/>
							<xs:pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idÁru" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="boltok_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="idBolt"/>
		</xs:key>
		<xs:keyref name="dolgozók_ForeignKey_1" refer="boltok_PrimaryKey_1">
			<xs:selector xpath="dolgozók"/>
			<xs:field xpath="idBolt"/>
		</xs:keyref>
	</xs:element>
<xs:element name="dolgozók" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idDolgozó">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="név">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="szig_szám">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="munkaviszony_kezdete" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:date">
							<xs:minInclusive value="1000-01-01"/>
							<xs:maxInclusive value="9999-12-31"/>
							<xs:pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Utca">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Hsz">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Irsz">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idBolt">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="dolgozók_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="idDolgozó"/>
		</xs:key>
	</xs:element>
<xs:element name="kategóriák" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idKategória">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="kategória_neve">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="kategóriába_tart_termékek_száma">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="kategóriák_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="idKategória"/>
		</xs:key>
		<xs:keyref name="áru_ForeignKey_1" refer="kategóriák_PrimaryKey_1">
			<xs:selector xpath="áru"/>
			<xs:field xpath="idKategória"/>
		</xs:keyref>
	</xs:element>
<xs:element name="nm_kapcsolat" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="áru_összértéke">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="áru_mennyisége">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="beszállítás_ideje" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:date">
							<xs:minInclusive value="1000-01-01"/>
							<xs:maxInclusive value="9999-12-31"/>
							<xs:pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idÁru">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idBeszállító">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
<xs:element name="áru" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idÁru">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="név">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Darabár">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="kategória">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="idKategória">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="áru_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="idÁru"/>
		</xs:key>
		<xs:keyref name="boltok_ForeignKey_1" refer="áru_PrimaryKey_1">
			<xs:selector xpath="boltok"/>
			<xs:field xpath="idÁru"/>
		</xs:keyref>
		<xs:keyref name="nm_kapcsolat_ForeignKey_1" refer="áru_PrimaryKey_1">
			<xs:selector xpath="nm_kapcsolat"/>
			<xs:field xpath="idÁru"/>
		</xs:keyref>
	</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== rekateglas/WWSAMBxmlGyak/XMLFeladatWwsamb/XMLWwsamb.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file///D:/TR_WWSAMB/xml/XMLFeladatWwsamb/XMLSchemaWwsamb.xsd">

	
	<besztel>
		<BeszTelSzam>+36(20)4559834</BeszTelSzam>
		<idBeszállító>1</idBeszállító>
	</besztel>
	<besztel>
		<BeszTelSzam>+36(30)6743211</BeszTelSzam>
		<idBeszállító>2</idBeszállító>
	</besztel>
	<besztel>
		<BeszTelSzam>+36(70)1137890</BeszTelSzam>
		<idBeszállító>3</idBeszállító>
	</besztel>
	<besztel>
		<BeszTelSzam>+36(20)3250840</BeszTelSzam>
		<idBeszállító>4</idBeszállító>
	</besztel>
	<besztel>
		<BeszTelSzam>+36(30)8077854</BeszTelSzam>
		<idBeszállító>5</idBeszállító>
	</besztel>
	<besztel>
		<BeszTelSzam>+36(20)4158920</BeszTelSzam>
		<idBeszállító>6</idBeszállító>
	</besztel>
	<beszállítók>
		<idBeszállító>1</idBeszállító>
		<beszállító_neve>Szkárosi Zsolt</beszállító_neve>
	</beszállítók>
	<beszállítók>
		<idBeszállító>2</idBeszállító>
		<beszállító_neve>Katona József</beszállító_neve>
	</beszállítók>
	<beszállítók>
		<idBeszállító>3</idBeszállító>
		<beszállító_neve>Kormos Béla</beszállító_neve>
	</beszállítók>
	<beszállítók>
		<idBeszállító>4</idBeszállító>
		<beszállító_neve>Fülöp Máté</beszállító_neve>
	</beszállítók>
	<beszállítók>
		<idBeszállító>5</idBeszállító>
		<beszállító_neve>Papp András</beszállító_neve>
	</beszállítók>
	<beszállítók>
		<idBeszállító>6</idBeszállító>
		<beszállító_neve>Illés Pista</beszállító_neve>
	</beszállítók>
	<boltok>
		<helye>Dunaharaszti</helye>
		<idBolt>1</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-04</árucsere_dátuma>
		<idÁru>4</idÁru>
	</boltok>
	<boltok>
		<helye>Pesterzsébet</helye>
		<idBolt>2</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-02</árucsere_dátuma>
		<idÁru>7</idÁru>
	</boltok>
	<boltok>
		<helye>Vác</helye>
		<idBolt>3</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-29</árucsere_dátuma>
		<idÁru>4</idÁru>
	</boltok>
	<boltok>
		<helye>X.kerület</helye>
		<idBolt>4</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-25</árucsere_dátuma>
		<idÁru>10</idÁru>
	</boltok>
	<boltok>
		<helye>Pécel</helye>
		<idBolt>5</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-25</árucsere_dátuma>
		<idÁru>2</idÁru>
	</boltok>
	<boltok>
		<helye>XVII.kerület</helye>
		<idBolt>6</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-10</árucsere_dátuma>
		<idÁru>9</idÁru>
	</boltok>
	<boltok>
		<helye>Gyömrő</helye>
		<idBolt>7</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-04</árucsere_dátuma>
		<idÁru>16</idÁru>
	</boltok>
	<boltok>
		<helye>Dunaharaszti</helye>
		<idBolt>8</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-30</árucsere_dátuma>
		<idÁru>12</idÁru>
	</boltok>
	<boltok>
		<helye>Vác</helye>
		<idBolt>9</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-12</árucsere_dátuma>
		<idÁru>5</idÁru>
	</boltok>
	<boltok>
		<helye>Pesterzsébet</helye>
		<idBolt>10</idBolt>
		<dolgozók_száma>1</dolgozók_száma>
		<árucsere_dátuma>2020-11-13</árucsere_dátuma>
		<idÁru>10</idÁru>
	</boltok>
	<dolgozók>
		<idDolgozó>1</idDolgozó>
		<név>Kis Éva</név>
		<szig_szám>123456AB</szig_szám>
		<munkaviszony_kezdete>2020-10-22</munkaviszony_kezdete>
		<Utca>Abos utca</Utca>
		<Hsz>21</Hsz>
		<Irsz>1024</Irsz>
		<idBolt>1</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>2</idDolgozó>
		<név>Nagy Anna</név>
		<szig_szám>243466AC</szig_szám>
		<munkaviszony_kezdete>2019-10-20</munkaviszony_kezdete>
		<Utca>Napsugaras utca</Utca>
		<Hsz>3</Hsz>
		<Irsz>1035</Irsz>
		<idBolt>2</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>3</idDolgozó>
		<név>Nagy Mária</név>
		<szig_szám>449428HK</szig_szám>
		<munkaviszony_kezdete>2020-07-07</munkaviszony_kezdete>
		<Utca>Dob utca</Utca>
		<Hsz>10</Hsz>
		<Irsz>2600</Irsz>
		<idBolt>3</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>4</idDolgozó>
		<név>Péterfi Katalin</név>
		<szig_szám>945486MA</szig_szám>
		<munkaviszony_kezdete>2019-08-12</munkaviszony_kezdete>
		<Utca>Hasznos utca</Utca>
		<Hsz>19</Hsz>
		<Irsz>1105</Irsz>
		<idBolt>4</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>5</idDolgozó>
		<név>Sárosi Zsófia</név>
		<szig_szám>665840JK</szig_szám>
		<munkaviszony_kezdete>2020-09-09</munkaviszony_kezdete>
		<Utca>Napsugár utca</Utca>
		<Hsz>10</Hsz>
		<Irsz>1173</Irsz>
		<idBolt>5</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>6</idDolgozó>
		<név>Miskolczi Panna</név>
		<szig_szám>145498NA</szig_szám>
		<munkaviszony_kezdete>2019-02-26</munkaviszony_kezdete>
		<Utca>Kis-Hunyad utca</Utca>
		<Hsz>12</Hsz>
		<Irsz>2119</Irsz>
		<idBolt>6</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>7</idDolgozó>
		<név>Kovács Eszter</név>
		<szig_szám>784512DK</szig_szám>
		<munkaviszony_kezdete>2019-05-10</munkaviszony_kezdete>
		<Utca>Gereben utca</Utca>
		<Hsz>48</Hsz>
		<Irsz>1019</Irsz>
		<idBolt>7</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>8</idDolgozó>
		<név>Tóth Erika</név>
		<szig_szám>649406PA</szig_szám>
		<munkaviszony_kezdete>2020-01-02</munkaviszony_kezdete>
		<Utca>Rőzse utca</Utca>
		<Hsz>67</Hsz>
		<Irsz>1205</Irsz>
		<idBolt>8</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>9</idDolgozó>
		<név>Németh Andrea</név>
		<szig_szám>981572BC</szig_szám>
		<munkaviszony_kezdete>2019-03-05</munkaviszony_kezdete>
		<Utca>Zsolna utca</Utca>
		<Hsz>34</Hsz>
		<Irsz>2230</Irsz>
		<idBolt>9</idBolt>
	</dolgozók>
	<dolgozók>
		<idDolgozó>10</idDolgozó>
		<név>Farkas Ilona</név>
		<szig_szám>832456DP</szig_szám>
		<munkaviszony_kezdete>2020-08-12</munkaviszony_kezdete>
		<Utca>Sályi utca</Utca>
		<Hsz>42</Hsz>
		<Irsz>1035</Irsz>
		<idBolt>10</idBolt>
	</dolgozók>
	<kategóriák>
		<idKategória>1</idKategória>
		<kategória_neve>extra</kategória_neve>
		<kategóriába_tart_termékek_száma>5</kategóriába_tart_termékek_száma>
	</kategóriák>
	<kategóriák>
		<idKategória>2</idKategória>
		<kategória_neve>krém</kategória_neve>
		<kategóriába_tart_termékek_száma>3</kategóriába_tart_termékek_száma>
	</kategóriák>
	<kategóriák>
		<idKategória>3</idKategória>
		<kategória_neve>A</kategória_neve>
		<kategóriába_tart_termékek_száma>5</kategóriába_tart_termékek_száma>
	</kategóriák>
	<kategóriák>
		<idKategória>4</idKategória>
		<kategória_neve>1</kategória_neve>
		<kategóriába_tart_termékek_száma>3</kategóriába_tart_termékek_száma>
	</kategóriák>
	<nm_kapcsolat>
		<áru_összértéke>10000</áru_összértéke>
		<áru_mennyisége>20</áru_mennyisége>
		<beszállítás_ideje>2020-11-03</beszállítás_ideje>
		<idÁru>1</idÁru>
		<idBeszállító>3</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>15000</áru_összértéke>
		<áru_mennyisége>15</áru_mennyisége>
		<beszállítás_ideje>2020-10-22</beszállítás_ideje>
		<idÁru>2</idÁru>
		<idBeszállító>2</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>5000</áru_összértéke>
		<áru_mennyisége>10</áru_mennyisége>
		<beszállítás_ideje>2020-11-12</beszállítás_ideje>
		<idÁru>3</idÁru>
		<idBeszállító>6</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>8000</áru_összértéke>
		<áru_mennyisége>5</áru_mennyisége>
		<beszállítás_ideje>2020-11-30</beszállítás_ideje>
		<idÁru>4</idÁru>
		<idBeszállító>5</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>10000</áru_összértéke>
		<áru_mennyisége>10</áru_mennyisége>
		<beszállítás_ideje>2020-12-02</beszállítás_ideje>
		<idÁru>5</idÁru>
		<idBeszállító>1</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>60000</áru_összértéke>
		<áru_mennyisége>8</áru_mennyisége>
		<beszállítás_ideje>2020-10-20</beszállítás_ideje>
		<idÁru>6</idÁru>
		<idBeszállító>4</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>10000</áru_összértéke>
		<áru_mennyisége>10</áru_mennyisége>
		<beszállítás_ideje>2020-11-19</beszállítás_ideje>
		<idÁru>7</idÁru>
		<idBeszállító>4</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>18000</áru_összértéke>
		<áru_mennyisége>12</áru_mennyisége>
		<beszállítás_ideje>2020-12-16</beszállítás_ideje>
		<idÁru>8</idÁru>
		<idBeszállító>3</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>20000</áru_összértéke>
		<áru_mennyisége>25</áru_mennyisége>
		<beszállítás_ideje>2020-10-14</beszállítás_ideje>
		<idÁru>9</idÁru>
		<idBeszállító>5</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>28000</áru_összértéke>
		<áru_mennyisége>30</áru_mennyisége>
		<beszállítás_ideje>2020-11-23</beszállítás_ideje>
		<idÁru>10</idÁru>
		<idBeszállító>1</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>13000</áru_összértéke>
		<áru_mennyisége>20</áru_mennyisége>
		<beszállítás_ideje>2020-11-05</beszállítás_ideje>
		<idÁru>11</idÁru>
		<idBeszállító>2</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>7000</áru_összértéke>
		<áru_mennyisége>8</áru_mennyisége>
		<beszállítás_ideje>2020-10-13</beszállítás_ideje>
		<idÁru>12</idÁru>
		<idBeszállító>6</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>9000</áru_összértéke>
		<áru_mennyisége>15</áru_mennyisége>
		<beszállítás_ideje>2020-12-21</beszállítás_ideje>
		<idÁru>13</idÁru>
		<idBeszállító>2</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>5000</áru_összértéke>
		<áru_mennyisége>20</áru_mennyisége>
		<beszállítás_ideje>2020-11-16</beszállítás_ideje>
		<idÁru>14</idÁru>
		<idBeszállító>5</idBeszállító>
	</nm_kapcsolat>
	<nm_kapcsolat>
		<áru_összértéke>11000</áru_összértéke>
		<áru_mennyisége>10</áru_mennyisége>
		<beszállítás_ideje>2020-11-30</beszállítás_ideje>
		<idÁru>15</idÁru>
